# Generated by Django 5.0.6 on 2024-06-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_remove_templateitem_product_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productininvoice',
            table='products_in_invoice',
        ),
        migrations.AlterModelTable(
            name='productintemplate',
            table='products_in_template',
        ),
        migrations.AlterModelTable(
            name='template',
            table='template',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
