# Generated by Django 5.0.6 on 2024-06-21 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_client_address_details_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payments_method',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
