# Generated by Django 5.0.6 on 2024-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_client_payments_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='payments_method',
        ),
        migrations.AddField(
            model_name='client',
            name='company_details',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
