# Generated by Django 5.0.6 on 2024-06-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_client_payments_method_client_company_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
