# Generated by Django 5.0.6 on 2024-06-21 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_invoice_date_alter_invoice_payments_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='payments_method',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='payments_status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payments_period',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_period',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 16, 25, 13, 638756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 16, 25, 13, 638756, tzinfo=datetime.timezone.utc)),
        ),
    ]
