# Generated by Django 5.0.6 on 2024-06-21 19:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_invoice_date_alter_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='details',
        ),
        migrations.RemoveField(
            model_name='template',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='template',
            name='status',
        ),
        migrations.AddField(
            model_name='template',
            name='frequnecy',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'In Cash'), ('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card'), ('PAYPAL', 'PayPal')], default='CREDIT', max_length=255),
        ),
        migrations.AddField(
            model_name='template',
            name='payment_period',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 19, 49, 18, 307968, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='template',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 19, 49, 18, 306972, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_period',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 19, 49, 18, 306972, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='template',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.client'),
        ),
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 19, 49, 18, 307968, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='template',
            name='number',
            field=models.CharField(default='', max_length=55, unique=True),
            preserve_default=False,
        ),
    ]
