# Generated by Django 5.0.6 on 2024-06-21 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_template_details_remove_template_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 19, 49, 34, 613409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_period',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 19, 49, 34, 613409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 19, 49, 34, 614408, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='template',
            name='payment_period',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 19, 49, 34, 614408, tzinfo=datetime.timezone.utc)),
        ),
    ]
