# Generated by Django 5.0.6 on 2024-06-21 19:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_invoice_date_alter_invoice_payment_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 19, 50, 5, 1858, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_period',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 19, 50, 5, 1858, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 19, 50, 5, 1858, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='template',
            name='frequnecy',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='template',
            name='payment_period',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 19, 50, 5, 1858, tzinfo=datetime.timezone.utc)),
        ),
    ]
