# Generated by Django 5.0.6 on 2024-06-21 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_invoice_date_alter_invoice_payment_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 19, 50, 57, 544236, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_period',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 19, 50, 57, 544236, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 19, 50, 57, 545236, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='template',
            name='payment_period',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 19, 50, 57, 545236, tzinfo=datetime.timezone.utc)),
        ),
    ]
